#
#
# Copyright Red Hat
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# See http://docs.codecov.io/docs/coverage-configuration
coverage:
  precision: 2 # 2 = xx.xx%, 0 = xx%
  round: down
  # For example: 20...60 would result in any coverage less than 20%
  # would have a red background. The color would gradually change to
  # green approaching 60%. Any coverage over 60% would result in a
  # solid green color.
  range: "20...60"

  status:
    # project will give us the diff in the total code coverage between a commit
    # and its parent
    project: yes
    # Patch gives just the coverage of the patch
    patch: yes
    # changes tells us if there are unexpected code coverage changes in other files
    # which were not changed by the diff
    changes: yes

  # See http://docs.codecov.io/docs/ignoring-paths
  ignore:
    - "assets/*"
    - "build/*"
    - "deploy/*"
    - "hack/*"
    - "manifests/*"
    - "openshift-ci/*"
    - "vendor/*"
    - "Makefile"
    - ".travis.yml"

# See http://docs.codecov.io/docs/pull-request-comments-1
comment:
  layout: "diff, files"
  behavior: ""
            # default = posts once then update, posts new if delete
            # once = post once then updates
            # new = delete old, post new
            # spammy = post new
