schemaVersion: 2.0.0
metadata:
  name: with-parent
parent:
  uri: https://raw.githubusercontent.com/che-incubator/devworkspace-api/proposal-25-variant-1-define-stacks/devfile-support/samples/nodejs-stack.devfile.yaml
  projects:
    - name: example
      git:
        checkoutFrom:
          revision: "mybranch"
commands:
  - id: sayhello
    exec:
      label: Say Hello
      commandLine: echo "hello"
      component: nodejs
