//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Generated for the devfile generator

// Code generated by helpgen. DO NOT EDIT.

package validate

import (
	"sigs.k8s.io/controller-tools/pkg/markers"
)

func (Generator) Help() *markers.DefinitionHelp {
	return &markers.DefinitionHelp{
		Category: "",
		DetailedHelp: markers.DetailedHelp{
			Summary: "validates the consistency of the API GO code. ",
			Details: "Validity checks are related to unions, patchStrategy, and optional fields.",
		},
		FieldHelp: map[string]markers.DetailedHelp{},
	}
}
