name: Task
description: 🔧 Issue for project support and quality assurance
labels:
  - kind/task
body:
  - type: dropdown
    attributes:
      label: Which area is this issue related to?
      description: Choose the area(s) this task is related to.
      multiple: true
      options:
        - /area ci
        - /area api
        - /area library
        - /area registry
        - /area registry-viewer
        - /area alizer
        - /area devworkspace
        - /area integration-tests
        - /area test-automation
        - /area releng
        - /area landing-page
    validations:
      required: true
  - type: textarea
    attributes:
      label: Issue Description
      description: A clear and concise description of what the task is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: Decide which specific steps need to be completed, outline subtasks.
      value: |
        - [ ] ....
        - [ ] ....
  - type: input
    attributes:
      label: Target Odo version
      description: Provide the target Odo version if this task is for QE integration test.
      value: 'Target Odo version: <odo-version>'