name: Documentation
description: 📖 Suggest an update for devfile documentation
labels:
  - area/documentation
body:
  - type: textarea
    attributes:
      label: Which area is this documentation change related to?
      description: Choose the area(s) this documentation change refer to.
      value: |
        > /area ci
        > /area api
        > /area library
        > /area registry
        > /area registry-viewer
        > /area alizer
        > /area devworkspace
        > /area integration-tests
        > /area test-automation
        > /area releng
        > /area landing-page
      placeholder: |
        > /area ci
        > /area api
        > /area library
        > /area registry
        > /area registry-viewer
        > /area alizer
        > /area devworkspace
        > /area integration-tests
        > /area test-automation
        > /area releng
        > /area landing-page
    validations:
      required: true
  - type: textarea
    attributes:
      label: Issue Details
      description: Provide a clear and concise description of the changes you are suggesting
      value: |
        **What mistake did you find / what is missing in the documentation?**
    validations:
      required: true