blank_issues_enabled: false
contact_links:
  - name: Devfile Community Slack Channel
    url: https://kubernetes.slack.com/archives/C02SX9E5B55
    about: Devfile Community Slack Channel in the Kubernetes Workspace.  If you haven’t joined the Kubernetes workspace before, follow https://slack.k8s.io/
