//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Generated for the devfile generator

// Code generated by helpgen. DO NOT EDIT.

package interfaces

import (
	"sigs.k8s.io/controller-tools/pkg/markers"
)

func (Generator) Help() *markers.DefinitionHelp {
	return &markers.DefinitionHelp{
		Category: "",
		DetailedHelp: markers.DetailedHelp{
			Summary: "generates GO source code required for the API ",
			Details: "Generated source code mainly consists in interface implementations to manage unions and keyed top-level lists",
		},
		FieldHelp: map[string]markers.DetailedHelp{},
	}
}
