// +build !ignore_autogenerated

// Generated for the devfile generator

// Code generated by helpgen. DO NOT EDIT.

package overrides

import (
	"sigs.k8s.io/controller-tools/pkg/markers"
)

func (FieldOverridesInclude) Help() *markers.DefinitionHelp {
	return &markers.DefinitionHelp{
		Category: "Overrides",
		DetailedHelp: markers.DetailedHelp{
			Summary: "drives whether a field should be overriden in devfile parent or plugins",
			Details: "",
		},
		FieldHelp: map[string]markers.DetailedHelp{
			"Omit": markers.DetailedHelp{
				Summary: "indicates that this field cannot be overriden in a devfile plugin.",
				Details: "",
			},
			"OmitInPlugin": markers.DetailedHelp{
				Summary: "OmmitInPlugin indicates that this field cannot be overriden in a devfile plugin.",
				Details: "",
			},
			"Description": markers.DetailedHelp{
				Summary: "indicates the description that should be added as Go documentation on the generated structs.",
				Details: "",
			},
		},
	}
}

func (Generator) Help() *markers.DefinitionHelp {
	return &markers.DefinitionHelp{
		Category: "",
		DetailedHelp: markers.DetailedHelp{
			Summary: "generates additional GO code for the overriding of elements in devfile parent or plugins.",
			Details: "",
		},
		FieldHelp: map[string]markers.DetailedHelp{
			"IsForPluginOverrides": markers.DetailedHelp{
				Summary: "indicates that the generated code should be done for plugin overrides. When false, the parent overrides are generated",
				Details: "",
			},
			"packageTypes": markers.DetailedHelp{
				Summary: "",
				Details: "",
			},
			"suffix": markers.DetailedHelp{
				Summary: "",
				Details: "",
			},
			"rootTypeToProcess": markers.DetailedHelp{
				Summary: "",
				Details: "",
			},
		},
	}
}
