kind: "DevWorkspace"
apiVersion: "workspace.devfile.io/v1alpha1"
metadata:
  "name": "myWorkspace"
spec:
  started: true
  routingClass: 'openshift-auth'
  template:
    projects:
      - name: "devworkspace-spec"
        git:
          remotes:
            origin: "https://github.com/che-incubator/devworkspace-api"
          checkoutFrom:
            revision: "master"
    components:
      - plugin:
          id: eclipse/che-theia/latest
      - plugin:
          name: "ownPlugin"
          id: acme/newPlugin/latest
          registryUrl: "https://acme.com/registry/"
      - plugin:
          name: "myPlugin"
          uri: "https://github.com/johndoe/che-plugins/blob/master/cool-plugin/0.0.1/meta.yaml"
      - container:
          image: "busybox"
          name: "mycontainer"
          memoryLimit: "128M"
          mountSources: true
          endpoints:
            - name: term-websockets
              protocol: ws
              attributes:
                type: terminal
              targetPort: 4000
      - custom:
          name: "myNewComponent"
          componentClass: "NewComponentType"
          embeddedResource:
            field1: ""
            field2: ""
      - kubernetes:
          name: "production"
          uri: "https://somewhere/production-environment.yaml"
