version: "2"

services:
  front-end:
    image: quay.io/mloriedo/universal-developer-image:buildah
    hostname: front-end
    expose:
      - 8079
    restart: always
    cap_drop:
      - all
    read_only: true
  catalogue:
    image: weaveworksdemos/catalogue:0.3.5
    hostname: catalogue
    expose:
      - 8080
    command: sh -c "sleep 30 && /app -port 8080 -DSN "catalogue_user:default_password@tcp(localhost:3306)/socksdb""
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
  catalogue-db:
    image: weaveworksdemos/catalogue-db:0.3.0
    hostname: catalogue-db
    expose:
      - 3360
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=fakepassword
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
    tmpfs:
      - /tmp:rw,noexec,nosuid
  carts:
    image: weaveworksdemos/carts:0.4.8
    hostname: carts
    expose:
      - 80
    command: sh -c "sleep 30 && /usr/local/bin/java.sh -Djava.security.egd=file:/dev/urandom -jar ./app.jar --port=80"
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
  carts-db:
    image: mongo:3.4
    hostname: carts-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    expose:
      - 27017
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
