name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  stale:

    permissions:
      issues: write  # for actions/stale to close stale issues
      pull-requests: write  # for actions/stale to close stale PRs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v7
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "This issue is stale because it has been open for 90 days with no activity. Remove stale label or comment or this will be closed in 60 days."
        stale-pr-message: "This PR is stale because it has been open for 90 days with no activity. Remove stale label or comment or this will be closed in 60 days."

        days-before-stale: 90
        days-before-close: 60
        stale-issue-label: 'lifecycle/stale'
        stale-pr-label: 'lifecycle/stale'
        exempt-issue-labels: 'lifecycle/frozen'
        exempt-pr-labels: 'lifecycle/frozen'
        close-issue-label: 'lifecycle/rotten'
        close-pr-label: 'lifecycle/rotten'

        start-date: '2023-03-16T00:00:00Z'

